package vidmatinsta.downloader.fullmovie.tube.socialmedia.downloadfreevidmata.statussaver.model.time_line;

import androidx.annotation.Keep;

import java.util.ArrayList;

import vidmatinsta.downloader.fullmovie.tube.socialmedia.downloadfreevidmata.statussaver.model.post.Caption;
import vidmatinsta.downloader.fullmovie.tube.socialmedia.downloadfreevidmata.statussaver.model.post.ClipsMetadata;
import vidmatinsta.downloader.fullmovie.tube.socialmedia.downloadfreevidmata.statussaver.model.post.CollabFollowButtonInfo;
import vidmatinsta.downloader.fullmovie.tube.socialmedia.downloadfreevidmata.statussaver.model.post.CommentInformTreatment;

@Keep
public class Media{
    public int taken_at;
    public long pk;
    public String id;
    public boolean hide_view_all_comment_entrypoint;
    public boolean is_visual_reply_commenter_notice_enabled;
    public boolean like_and_view_counts_disabled;
    public boolean is_post_live_clips_media;
    public boolean is_reshare_of_text_post_app_media_in_ig;
    public boolean comment_threading_enabled;
    public boolean is_unified_video;
    public boolean has_privately_liked;
    public String commerciality_status;
    public int filter_type;
    public String client_cache_key;
    public String integrity_review_decision;
    public long fbid;
    public long device_timestamp;
    public boolean caption_is_edited;
    public String strong_id__;
    public int deleted_reason;
    public int has_shared_to_fb;
    public boolean should_request_ads;
    public boolean has_delayed_metadata;
    public String logging_info_token;
    public String mezql_token;
    public String algorithm;
    public String connection_id;
    public ArrayList<Object> preview_comments;
    public int comment_count;
    public boolean is_comments_gif_composer_enabled;
    public CommentInformTreatment comment_inform_treatment;
    public boolean has_liked;
    public int like_count;
    public ArrayList<Object> facepile_top_likers;
    public ArrayList<Object> top_likers;
    public double video_subtitles_confidence;
    public String video_subtitles_locale;
    public int is_dash_eligible;
    public String video_dash_manifest;
    public String video_codec;
    public int number_of_qualities;
    public ArrayList<VideoVersion> video_versions;
    public double video_duration;
    public boolean has_audio;
    public ArrayList<Object> clips_tab_pinned_user_ids;
    public ClipsMetadata clips_metadata;
    public boolean can_viewer_reshare;
    public boolean is_organic_product_tagging_eligible;
    public ArrayList<Object> product_suggestions;
    public boolean can_view_more_preview_comments;
    public boolean has_more_comments;
    public int max_num_visible_preview_comments;
    public boolean explore_hide_comments;
    public boolean is_open_to_public_submission;
    public boolean can_see_insights_as_brand;
    public int media_type;
    public String code;
    public Caption caption;
    public SharingFrictionInfo sharing_friction_info;
    public int play_count;
    public MediaAppreciationSettings media_appreciation_settings;
    public ArrayList<Object> creator_viewer_insights;
    public FbUserTags fb_user_tags;
    public ArrayList<Object> invited_coauthor_producers;
    public boolean is_in_profile_grid;
    public boolean profile_grid_control_enabled;
    public User user;
    public ImageVersions2 image_versions2;
    public int original_width;
    public int original_height;
    public boolean is_artist_pick;
    public boolean enable_media_notes_production;
    public String product_type;
    public boolean is_paid_partnership;
    public String inventory_source;
    public String organic_tracking_token;
    public boolean is_third_party_downloads_eligible;
    public boolean ig_media_sharing_disabled;
    public boolean are_remixes_crosspostable;
    public Explore explore;
    public String explore_context;
    public boolean subscribe_cta_visible;
    public boolean is_auto_created;
    public boolean is_cutout_sticker_allowed;
    public String recommendation_data;
    public Owner owner;
    public int fb_aggregated_like_count;
    public int fb_aggregated_comment_count;
    public boolean is_tagged_media_shared_to_viewer_profile_grid;
    public boolean should_show_author_pog_for_tagged_media_shared_to_profile_grid;
    public String impression_token;
}